[package]
name = "dy-sv5w"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.1"

[dev-dependencies]
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros", "time"] }
